### ISSUE TITLE
[no-unused-vars] Crash when running ESLint

### ISSUE THREAD

**Issue by ficristo** [bradzacher/eslint-plugin-typescript#171]
**Repro**

```JSON
{
  "rules": {
    "no-unused-vars": [1, {"vars": "all", "args": "none"}],
    "typescript/no-unused-vars": "warn"
  }
}
```

I cannot hunt down the code where it breaks

**Expected Result**
ESLint should pass.

**Actual Result**
```
Warning: Cannot read property 'type' of undefined Use --force to continue.
TypeError: Cannot read property 'type' of undefined
    at isForInRef (F:\github\quadre\node_modules\eslint\lib\rules\no-unused-vars.js:406:24)
    at variable.references.some.ref (F:\github\quadre\node_modules\eslint\lib\rules\no-unused-vars.js:443:21)
    at Array.some (<anonymous>)
    at isUsedVariable (F:\github\quadre\node_modules\eslint\lib\rules\no-unused-vars.js:442:40)
    at collectUnusedVariables (F:\github\quadre\node_modules\eslint\lib\rules\no-unused-vars.js:565:26)
    at collectUnusedVariables (F:\github\quadre\node_modules\eslint\lib\rules\no-unused-vars.js:572:17)
    at collectUnusedVariables (F:\github\quadre\node_modules\eslint\lib\rules\no-unused-vars.js:572:17)
    at Program:exit (F:\github\quadre\node_modules\eslint\lib\rules\no-unused-vars.js:617:36)
    at listeners.(anonymous function).forEach.listener (F:\github\quadre\node_modules\eslint\lib\util\safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
```

**Additional Info**
At the moment I cannot update ESLint to version 5.*
See also https://github.com/eslint/typescript-eslint-parser/issues/553

See quadre-code/quadre#103 where I upgraded typescript-eslint-parser, when I got this error.
Trying to use this plugin didn't fix the crash.
To see the error on my project I run grunt eslint --stack --debug.

**Versions**

| package                    | version |
| -------------------------- | ------- |
| `eslint-plugin-typescript` | `0.13.0` |
| `typescript-eslint-parser` | `21.0.1` |
| `typescript`               | `3.1.6` |
| `eslint` | `4.19.1` |

**Comment by j-f1** [comment]
Does my suggestion in #170 help here?

**Comment by bradzacher** [comment]
I would hazard a guess that this is a bug introduced by `typescript-eslint-parser@21`.

**Comment by ficristo** [comment]
My previous version was 15.0.0 and ESLint worked. For now I just disabled the rule on ts and tsx code, so to be able to upgrade the parser.

**Comment by armano2** [comment]
@ficristo do you mind trying to run eslint from console with `--debug` flag?
it should print you additional data to locate line

**Comment by ficristo** [comment]
Running this
`node_modules/.bin/eslint --ext .tsx,.ts --ignore-path .gitignore --debug . &> result.txt`

Here the [result.txt](https://github.com/bradzacher/eslint-plugin-typescript/files/2601455/result.txt)

**Comment by armano2** [comment]
@ficristo in src\extensions\default\quadre-whitespaces\main.ts
you have something like this
```
enum FOO {
PROP
PROP2
```
and next token is failing

**Comment by ficristo** [comment]
Fixed upstream.
