### ISSUE TITLE
[no-unused-vars] crashes with initialized enums

### ISSUE THREAD

**Issue by targos** [bradzacher/eslint-plugin-typescript#193]
**Repro**

```JSON
{
  "rules": {
    "no-unused-vars": "error",
    "typescript/no-unused-vars": "error"
  }
}
```

```TS
export enum Environment {
  development = 'development',
  staging = 'staging',
  production = 'production'
}
```

**Expected Result**

No error.

**Actual Result**

The `no-unused-vars` core rule's code of ESLint crashes.

**Additional Info**

Stack trace:
```
TypeError: Cannot read property 'type' of undefined
    at isForInRef (D:\project\node_modules\eslint\lib\rules\no-unused-vars.js:436:18)
    at variable.references.some (D:\project\node_modules\eslint\lib\rules\no-unused-vars.js:474:13)
    at Array.some (<anonymous>)
    at isUsedVariable (D:\project\node_modules\eslint\lib\rules\no-unused-vars.js:473:34)
    at collectUnusedVariables (D:\project\node_modules\eslint\lib\rules\no-unused-vars.js:613:14)
    at collectUnusedVariables (D:\project\node_modules\eslint\lib\rules\no-unused-vars.js:623:9)
    at collectUnusedVariables (D:\project\node_modules\eslint\lib\rules\no-unused-vars.js:623:9)
    at Program:exit (D:\project\node_modules\eslint\lib\rules\no-unused-vars.js:673:28)
    at listeners.(anonymous function).forEach.listener (D:\project\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
```

**Versions**

| package                    | version |
| -------------------------- | ------- |
| `eslint`                   | `5.9.0` |
| `eslint-plugin-typescript` | `0.14.0` |
| `typescript-eslint-parser` | `21.0.1` |
| `typescript`               | `3.1.6` |

**Comment by bradzacher** [comment]
Downgrade your version of `typescript-eslint-parser` to `^17` and let me know if the issue persists

**Comment by armano2** [comment]
issue is in parser, and got fixed in https://github.com/eslint/typescript-eslint-parser/commit/491ebcaff9815071d4194584e3d94d0edf601e3b

**Comment by targos** [comment]
Oh, I see. I just realized that this package relies on a specific version of the typescript parser, sorry.
