### ISSUE TITLE
ESLint error: Cannot find module 'eslint-plugin-typescript/parser'

### ISSUE THREAD

**Issue by wolfy1339** [bradzacher/eslint-plugin-typescript#199]
When trying to run ESLint with this plugin, I get an error:
```
./node_modules/.bin/eslint bot/**/*.ts --ext .ts
Error: Cannot find module 'eslint-plugin-typescript/parser'
    at ModuleResolver.resolve (C:\Users\<user>\Desktop\Programming\github-notification-service\node_modules\eslint\lib\util\module-resolver.js:72:19)
    at loadFromDisk (C:\Users\<user>\Desktop\Programming\github-notification-service\node_modules\eslint\lib\config\config-file.js:514:42)
    at Object.load (C:\Users\<user>\Desktop\Programming\github-notification-service\node_modules\eslint\lib\config\config-file.js:564:20)
    at Config.getLocalConfigHierarchy (C:\Users\<user>\Desktop\Programming\github-notification-service\node_modules\eslint\lib\config.js:227:44)
    at Config.getConfigHierarchy (C:\Users\<user>\Desktop\Programming\github-notification-service\node_modules\eslint\lib\config.js:179:43)
    at Config.getConfigVector (C:\Users\<user>\Desktop\Programming\github-notification-service\node_modules\eslint\lib\config.js:286:21)
    at Config.getConfig (C:\Users\<user>\Desktop\Programming\github-notification-service\node_modules\eslint\lib\config.js:329:29)
    at processText (C:\Users\<user>\Desktop\Programming\github-notification-service\node_modules\eslint\lib\cli-engine.js:180:33)
    at processFile (C:\Users\<user>\Desktop\Programming\github-notification-service\node_modules\eslint\lib\cli-engine.js:240:12)
    at fileList.map.fileInfo (C:\Users\<user>\Desktop\Programming\github-notification-service\node_modules\eslint\lib\cli-engine.js:612:40)
```
ESLint version: 5.9.0
eslint-plugin-typescript version: 0.14.0
Node v11

**Comment by bradzacher** [comment]
Hi @wolfy1339,
The readme changes are part of the upcoming 1.0.0 release.
For the current release readme, please see the tag corresponding to the release (0.14.0), or see the readme on npm.

Duplicate of #198
Please use the search next time.
